version: 2

models:
  - name: dim_customers
    description: '{{ doc("customers") }}'
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order.